### ISSUE TITLE
Silently returns zero results

### ISSUE THREAD

**Issue by kclevenger** [tkem/mopidy-internetarchive#64]
About 6 week ago Mopidy-InternetArchive started silently returning zero results when browsing on Title or Views [ex: Internet Archive/Old Time Radio/Title]

Mopidy (2.0.1)
Mopidy-InternetArchive (2.0.0)

~~~
INFO     New MPD connection from [::ffff:127.0.0.1]:39040
ERROR    InternetArchiveBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_internetarchive/library.py", line 45, in browse
    return self.__browse_collection(identifier, **query)
  File "/usr/lib/python2.7/site-packages/mopidy_internetarchive/library.py", line 122, in __browse_collection
    sort=sort
  File "/usr/lib/python2.7/site-packages/mopidy_internetarchive/translator.py", line 119, in ref
    return Ref.album(name=name, uri=uri(identifier))
  File "/usr/lib/python2.7/site-packages/mopidy/models/__init__.py", line 59, in album
    return cls(**kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy/models/immutable.py", line 158, in __call__
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy/models/immutable.py", line 34, in __init__
    self._set_field(key, value)
  File "/usr/lib/python2.7/site-packages/mopidy/models/immutable.py", line 186, in _set_field
    object.__setattr__(self, name, value)
  File "/usr/lib/python2.7/site-packages/mopidy/models/fields.py", line 50, in __set__
    value = self.validate(value)
  File "/usr/lib/python2.7/site-packages/mopidy/models/fields.py", line 37, in validate
    (self._name, self._type, value))
TypeError: Expected name to be a <type 'basestring'>, not [u'Academy Awards Ceremonies', u'Academy Awards Ceremonies']
~~~

**Comment by tkem** [comment]
Thanks for reporting! Will look into this ASAP, but will probably have to wait until after the holidays.

**Comment by tkem** [comment]
@kclevenger: Sorry it took quite a while, but this should be fixed with Mopidy-InternetArchive v2.0.1 available via pip now.

**Comment by kclevenger** [comment]
I get farther into the structure now but it still wont list tracks:

Browse: Internet Archive/Old Time Radio/Title/Night Beat

ERROR    InternetArchiveBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_internetarchive/library.py", line 47, in browse
    return self.__browse_item(identifier)
  File "/usr/lib/python2.7/site-packages/mopidy_internetarchive/library.py", line 131, in __browse_item
    tracks = self.__tracks(item)
  File "/usr/lib/python2.7/site-packages/mopidy_internetarchive/library.py", line 158, in __tracks
    tracks = translator.tracks(item, self.__audio_formats)
  File "/usr/lib/python2.7/site-packages/mopidy_internetarchive/translator.py", line 178, in tracks
    name=name(obj),
  File "/usr/lib/python2.7/site-packages/mopidy_internetarchive/translator.py", line 118, in name
    return obj['identifier']
KeyError: u'identifier'

**Comment by tkem** [comment]
This is interesting. I just tried and can browse/play "Night Beat" without problems (though I had to increase my `internetarchive/browse_limit` to access it via `Title`). Would you mind posting your mopidy config as reported by
```
mopidy config
```
or
```
sudo mopidyctl config
```
if you're running Mopidy as a service?

**Comment by kclevenger** [comment]
Attached
[mopidy_config.txt](https://github.com/tkem/mopidy-internetarchive/files/694107/mopidy_config.txt)

**Comment by tkem** [comment]
Thanks, can reproduce now.
Stay tuned ;-)

**Comment by tkem** [comment]
@kclevenger: Do you have this issue with other collections than "Night Beat", too?
There seem to be two (2!!!) collections named "Night Beat" on Old Time Radio, one with ID "NightBeat" and 3 items/shows, and one with ID "Nightbeat_otr" and > 6 shows. Only the latter ("Nightbeat_otr") seems to trigger this!
*sigh*

**Comment by kclevenger** [comment]
Some directories with a larger number of files like Suspense are OK, and others with a smaller number like the yearly 40's Fibber McGee are a problem. Seems like it's not related to number of tracks. 

Browse: Internet Archive/Old Time Radio/Title/Dragnet - Single Episodes - OK

Browse: Internet Archive/Old Time Radio/Title/ElleryQueen - fail
Browse: Internet Archive/Old Time Radio/Title/Ellery Queen - OK, but only one track

Browse: Internet Archive/Old Time Radio/Title/Fibber McGee and Molly - 1942 - OK
Browse: Internet Archive/Old Time Radio/Title/Fibber McGee and Molly 1943 - OK
Browse: Internet Archive/Old Time Radio/Title/Fibber McGee and Molly 194[4-9] - fail
Browse: Internet Archive/Old Time Radio/Title/Fibber McGee and Molly 1951 - OK
Browse: Internet Archive/Old Time Radio/Title/Fibber McGee and Molly 1952 - OK

Browse: Internet Archive/Old Time Radio/Title/Suspense - Single Episodes - OK

**Comment by tkem** [comment]
@kclevenger: I just uploaded v2.0.2, which lets me browse/play at least both "Night Beat" versions.
Please give it a try and feel free to reopen this if you experience any problems.
Thanks!

**Comment by kclevenger** [comment]
That's got it, thank you!

**Comment by tkem** [comment]
No, thank *you*!
